In [2]:
from google.colab import drive
from os.path import join
ROOT = "/content/drive"
print(ROOT)
drive.mount(ROOT)

/content/drive
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [10]:
from os.path import join  

# path to your project on Google Drive
MY_GOOGLE_DRIVE_PATH = '/content/drive/MyDrive/git-colab' 
# replace with your Github username 
GIT_USERNAME = "Jeremy-su1" 
# definitely replace with your
GIT_TOKEN = "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"  
# Replace with your github repository in this case we want 
# to clone deep-learning-v2-pytorch repository
GIT_REPOSITORY = "ML-colab" 

PROJECT_PATH = join(ROOT, MY_GOOGLE_DRIVE_PATH)

# It's good to print out the value if you are not sure 
print("PROJECT_PATH: ", PROJECT_PATH)   

# In case we haven't created the folder already; we will create a folder in the project path 
!mkdir "{PROJECT_PATH}"    

#GIT_PATH = "https://{GIT_TOKEN}@github.com/{GIT_USERNAME}/{GIT_REPOSITORY}.git" this return 400 Bad Request for me
GIT_PATH = "https://" + GIT_TOKEN + "@github.com/" + GIT_USERNAME + "/" + GIT_REPOSITORY + ".git"
print("GIT_PATH: ", GIT_PATH)

PROJECT_PATH:  /content/drive/MyDrive/git-colab
mkdir: cannot create directory ‘/content/drive/MyDrive/git-colab’: File exists
GIT_PATH:  https://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@github.com/Jeremy-su1/ML-colab.git


In [16]:
%cd "{PROJECT_PATH}" 
!pwd   # Change directory to the location defined in project_path
!git clone "{GIT_PATH}"  # clone the github repository

/content/drive/MyDrive/git-colab
/content/drive/MyDrive/git-colab
Cloning into 'ML-colab'...


In [13]:
!git config --global user.email 'ahn.suwon725@gmail.com'
!git config --global user.name 'jeremy-su1'

In [20]:
%cd "{PROJECT_PATH}/ML-colab" 
!git add .
!git commit -m "update first test"
!git push -u origin master


/content/drive/MyDrive/git-colab/ML-colab
[master (root-commit) 078d7ef] update first test
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 a.txt
Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Writing objects: 100% (3/3), 215 bytes | 21.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To https://github.com/Jeremy-su1/ML-colab.git
 * [new branch]      master -> master
Branch 'master' set up to track remote branch 'master' from 'origin'.


In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
s1 = 3.14
s2 = 100
s3 = 'korea'

In [ ]:
# Tensorflow constant = 고정값을 의미
c1 = tf.constant(s1)
c1

<tf.Tensor: shape=(), dtype=float32, numpy=3.14>

In [ ]:
c3 = tf.constant(s3)
c3

<tf.Tensor: shape=(), dtype=string, numpy=b'korea'>

In [ ]:
# 요소별 연산 (element wise)
a = tf.constant(3)
b = tf.constant([1,2,3])
# Operation Function (multiply)
c = tf.multiply(a,b)
c

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 6, 9], dtype=int32)>

In [ ]:
#numpy nd array 객체
c.numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 6, 9], dtype=int32)>>

In [ ]:
# d = c+a
d = tf.add(c,a)
d

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 6,  9, 12], dtype=int32)>

In [ ]:
# Element Broadcasting
e = tf.constant( [1,2,3])
# f의 경우에는 list 중첩 필요
f = tf.constant([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

# tf.add(e,f)
g = e+f
g

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12],
       [11, 13, 15]], dtype=int32)>

In [ ]:
h = tf.constant([ [1,2],[3,4]])
i = tf.constant([ [5,6],[7,8]])

# Element wise X
# h*i
j = tf.multiply(h,i)
j

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]], dtype=int32)>

In [ ]:
# 행렬과 행렬간의 행렬 곱
k = tf.matmul(h,i)
k

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]], dtype=int32)>